/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.gerador;

import algoritmos.gerador.AlgoritmoPrincipalGerador;
import ficha_personagem.Classes;
import ficha_personagem.Ficha;
import javax.swing.JOptionPane;

/**
 *
 * @author 422UR4H
 */
public class View_bonusLivre extends javax.swing.JDialog {

    /**
     * Creates new form View_bonusLivre
     * @param parent
     * @param modal
     */
    public View_bonusLivre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        // meu codigo
        
        Ficha ficha = AlgoritmoPrincipalGerador.getFicha();
        
        // setando pontos bonus de pericia
        switch (Classes.get(ficha.getClasse()).getTamBLivre()) {
            case 1:
                jLabelp1.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(0)));
                break;
            case 2:
                jLabelp1.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(0)));
                jLabelp2.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(1)));
                break;
            case 3:
                jLabelp1.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(0)));
                jLabelp2.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(1)));
                jLabelp3.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(2)));
                break;
            case 4:
                jLabelp1.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(0)));
                jLabelp2.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(1)));
                jLabelp3.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(2)));
                jLabelp4.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(3)));
                break;
            case 5:
                jLabelp1.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(0)));
                jLabelp2.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(1)));
                jLabelp3.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(2)));
                jLabelp4.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(3)));
                jLabelp5.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(4)));
                break;
            case 6:
                jLabelp1.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(0)));
                jLabelp2.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(1)));
                jLabelp3.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(2)));
                jLabelp4.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(3)));
                jLabelp5.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(4)));
                jLabelp6.setText("+"+String.valueOf(Classes.get(ficha.getClasse()).getBLivre(5)));
                break;
        }
        
        // setando valores de atributo
        jLabelValCar.setText(String.valueOf(ficha.getIniCar()));
        jLabelValCon.setText(String.valueOf(ficha.getIniCon()));
        jLabelValDex.setText(String.valueOf(ficha.getIniDex()));
        jLabelValFor.setText(String.valueOf(ficha.getIniFor()));
        jLabelValInt.setText(String.valueOf(ficha.getIniInt()));
        jLabelValMen.setText(String.valueOf(ficha.getIniMen()));
        
        // setando modificadores de atributo
        jLabelModCar.setText(String.valueOf(ficha.getModCar()));
        jLabelModFor.setText(String.valueOf(ficha.getModFor()));
        jLabelModCon.setText(String.valueOf(ficha.getModCon()));
        jLabelModInt.setText(String.valueOf(ficha.getModInt()));
        jLabelModMen.setText(String.valueOf(ficha.getModMen()));
        jLabelModDex.setText(String.valueOf(ficha.getModDex()));
        
        // setando pericias de atributo
        jLabelPerCar.setText(String.valueOf(ficha.getPerCar()));
        jLabelPerFor.setText(String.valueOf(ficha.getPerFor()));
        jLabelPerCon.setText(String.valueOf(ficha.getPerCon()));
        jLabelPerInt.setText(String.valueOf(ficha.getPerInt()));
        jLabelPerMen.setText(String.valueOf(ficha.getPerMen()));
        jLabelPerDex.setText(String.valueOf(ficha.getPerDex()));
        
        // fim do meu codigo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldBDex = new javax.swing.JTextField();
        jLabelp1 = new javax.swing.JLabel();
        jLabelPerDex = new javax.swing.JLabel();
        jButton = new javax.swing.JButton();
        jLabelModDex = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelValDex = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldBInt = new javax.swing.JTextField();
        jLabelPerInt = new javax.swing.JLabel();
        jLabelp5 = new javax.swing.JLabel();
        jLabelModInt = new javax.swing.JLabel();
        jLabelp4 = new javax.swing.JLabel();
        jLabelValInt = new javax.swing.JLabel();
        jLabelp3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelp2 = new javax.swing.JLabel();
        jLabelPerFor = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabelModFor = new javax.swing.JLabel();
        jTextFieldBCar = new javax.swing.JTextField();
        jLabelValFor = new javax.swing.JLabel();
        jLabelPerCar = new javax.swing.JLabel();
        jLabelModCar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelValCar = new javax.swing.JLabel();
        jLabelp6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldBCon = new javax.swing.JTextField();
        jLabelPerCon = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabelModCon = new javax.swing.JLabel();
        jTextFieldBMen = new javax.swing.JTextField();
        jLabelValCon = new javax.swing.JLabel();
        jLabelPerMen = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelModMen = new javax.swing.JLabel();
        jTextFieldBFor = new javax.swing.JTextField();
        jLabelValMen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bonus Livre");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jTextFieldBDex.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldBDex.setForeground(new java.awt.Color(0, 255, 0));
        jTextFieldBDex.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBDex.setText("0");
        jTextFieldBDex.setCaretColor(new java.awt.Color(0, 255, 0));
        jTextFieldBDex.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldBDex.setSelectionColor(new java.awt.Color(0, 255, 255));
        jTextFieldBDex.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBDexFocusGained(evt);
            }
        });

        jLabelp1.setBackground(new java.awt.Color(51, 51, 51));
        jLabelp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelp1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPerDex.setBackground(new java.awt.Color(51, 51, 51));
        jLabelPerDex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPerDex.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton.setBackground(new java.awt.Color(51, 51, 51));
        jButton.setText("Distribuir");
        jButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jLabelModDex.setBackground(new java.awt.Color(51, 51, 51));
        jLabelModDex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelModDex.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel33.setBackground(new java.awt.Color(102, 102, 102));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("BONUS");

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("For: ");

        jLabelValDex.setBackground(new java.awt.Color(51, 51, 51));
        jLabelValDex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelValDex.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel32.setBackground(new java.awt.Color(102, 102, 102));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("PER");

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Pontos livres de proficiencia:");

        jLabel31.setBackground(new java.awt.Color(102, 102, 102));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("MOD");

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Distribua corretamente os pontos");

        jLabel30.setBackground(new java.awt.Color(102, 102, 102));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("VAL");

        jLabel21.setBackground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Car: ");

        jTextFieldBInt.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldBInt.setForeground(new java.awt.Color(0, 255, 0));
        jTextFieldBInt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBInt.setText("0");
        jTextFieldBInt.setCaretColor(new java.awt.Color(0, 255, 0));
        jTextFieldBInt.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldBInt.setSelectionColor(new java.awt.Color(0, 255, 255));
        jTextFieldBInt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBIntFocusGained(evt);
            }
        });

        jLabelPerInt.setBackground(new java.awt.Color(51, 51, 51));
        jLabelPerInt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPerInt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelp5.setBackground(new java.awt.Color(51, 51, 51));
        jLabelp5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelp5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelModInt.setBackground(new java.awt.Color(51, 51, 51));
        jLabelModInt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelModInt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelp4.setBackground(new java.awt.Color(51, 51, 51));
        jLabelp4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelp4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelValInt.setBackground(new java.awt.Color(51, 51, 51));
        jLabelValInt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelValInt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelp3.setBackground(new java.awt.Color(51, 51, 51));
        jLabelp3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelp3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel17.setBackground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Int: ");

        jLabelp2.setBackground(new java.awt.Color(51, 51, 51));
        jLabelp2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelp2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPerFor.setBackground(new java.awt.Color(51, 51, 51));
        jLabelPerFor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPerFor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel25.setBackground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Men: ");

        jLabelModFor.setBackground(new java.awt.Color(51, 51, 51));
        jLabelModFor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelModFor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldBCar.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldBCar.setForeground(new java.awt.Color(0, 255, 0));
        jTextFieldBCar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBCar.setText("0");
        jTextFieldBCar.setCaretColor(new java.awt.Color(0, 255, 0));
        jTextFieldBCar.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldBCar.setSelectionColor(new java.awt.Color(0, 255, 255));
        jTextFieldBCar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBCarFocusGained(evt);
            }
        });

        jLabelValFor.setBackground(new java.awt.Color(51, 51, 51));
        jLabelValFor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelValFor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPerCar.setBackground(new java.awt.Color(51, 51, 51));
        jLabelPerCar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPerCar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelModCar.setBackground(new java.awt.Color(51, 51, 51));
        jLabelModCar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelModCar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Digite apenas valores numéricos!");

        jLabelValCar.setBackground(new java.awt.Color(51, 51, 51));
        jLabelValCar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelValCar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelp6.setBackground(new java.awt.Color(51, 51, 51));
        jLabelp6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelp6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Dex: ");

        jTextFieldBCon.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldBCon.setForeground(new java.awt.Color(0, 255, 0));
        jTextFieldBCon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBCon.setText("0");
        jTextFieldBCon.setCaretColor(new java.awt.Color(0, 255, 0));
        jTextFieldBCon.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldBCon.setSelectionColor(new java.awt.Color(0, 255, 255));
        jTextFieldBCon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBConFocusGained(evt);
            }
        });

        jLabelPerCon.setBackground(new java.awt.Color(51, 51, 51));
        jLabelPerCon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPerCon.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel29.setBackground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("ATR");

        jLabelModCon.setBackground(new java.awt.Color(51, 51, 51));
        jLabelModCon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelModCon.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldBMen.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldBMen.setForeground(new java.awt.Color(0, 255, 0));
        jTextFieldBMen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBMen.setText("0");
        jTextFieldBMen.setCaretColor(new java.awt.Color(0, 255, 0));
        jTextFieldBMen.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldBMen.setSelectionColor(new java.awt.Color(0, 255, 255));
        jTextFieldBMen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBMenFocusGained(evt);
            }
        });

        jLabelValCon.setBackground(new java.awt.Color(51, 51, 51));
        jLabelValCon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelValCon.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPerMen.setBackground(new java.awt.Color(51, 51, 51));
        jLabelPerMen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPerMen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Con: ");

        jLabelModMen.setBackground(new java.awt.Color(51, 51, 51));
        jLabelModMen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelModMen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldBFor.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldBFor.setForeground(new java.awt.Color(0, 255, 0));
        jTextFieldBFor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldBFor.setText("0");
        jTextFieldBFor.setCaretColor(new java.awt.Color(0, 255, 0));
        jTextFieldBFor.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldBFor.setSelectionColor(new java.awt.Color(0, 255, 255));
        jTextFieldBFor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBForFocusGained(evt);
            }
        });

        jLabelValMen.setBackground(new java.awt.Color(51, 51, 51));
        jLabelValMen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelValMen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel25))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabelValFor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelModFor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelPerFor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextFieldBInt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldBFor)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelValInt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelModInt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelPerInt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabelValCon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelModCon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelPerCon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabelValDex, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelModDex, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelPerDex, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabelValCar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelModCar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelPerCar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabelValMen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelModMen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabelPerMen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldBCar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldBMen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldBCon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldBDex, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabelp1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelp2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelp3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelp4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelp5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelp6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelp1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelp2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelp3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelp4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelp5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelp6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelValFor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelModFor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPerFor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldBFor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelValCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelModCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPerCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldBCon, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelValDex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelModDex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPerDex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldBDex, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelValInt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelModInt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPerInt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldBInt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelValCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelModCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPerCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldBCar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelValMen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelModMen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPerMen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldBMen, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBForFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBForFocusGained
        jTextFieldBFor.selectAll();
    }//GEN-LAST:event_jTextFieldBForFocusGained

    private void jTextFieldBConFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBConFocusGained
        jTextFieldBCon.selectAll();
    }//GEN-LAST:event_jTextFieldBConFocusGained

    private void jTextFieldBDexFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBDexFocusGained
        jTextFieldBDex.selectAll();
    }//GEN-LAST:event_jTextFieldBDexFocusGained

    private void jTextFieldBIntFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBIntFocusGained
        jTextFieldBInt.selectAll();
    }//GEN-LAST:event_jTextFieldBIntFocusGained

    private void jTextFieldBCarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBCarFocusGained
        jTextFieldBCar.selectAll();
    }//GEN-LAST:event_jTextFieldBCarFocusGained

    private void jTextFieldBMenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBMenFocusGained
        jTextFieldBMen.selectAll();
    }//GEN-LAST:event_jTextFieldBMenFocusGained

    private boolean validarDistribuicao(Ficha ficha) {
        try {
            // somando valores para testar se está correto
            int soma = 0;
            soma += Integer.parseInt(jTextFieldBFor.getText());
            soma += Integer.parseInt(jTextFieldBCon.getText());
            soma += Integer.parseInt(jTextFieldBDex.getText());
            soma += Integer.parseInt(jTextFieldBInt.getText());
            soma += Integer.parseInt(jTextFieldBCar.getText());
            soma += Integer.parseInt(jTextFieldBMen.getText());

            if (soma != Classes.get(ficha.getClasse()).getSomaBonus()) {
                JOptionPane.showMessageDialog(null, "Distribua a quantidade correta de pontos!",
                    "Error!", JOptionPane.ERROR_MESSAGE);
                return false;
            }

            // verificando se não foi distribuido per livre em atributos já incrementados
            if (!jTextFieldBFor.getText().equals("0") && ficha.getbFor() != 0) {
                JOptionPane.showMessageDialog(null, "Sua classe já lhe dá bonus de For!",
                    "Error!", JOptionPane.ERROR_MESSAGE);
                
                return false;
            }
            if (!jTextFieldBCon.getText().equals("0") && ficha.getbCon() != 0) {
                JOptionPane.showMessageDialog(null, "Sua classe já lhe dá bonus de Con!",
                    "Error!", JOptionPane.ERROR_MESSAGE);
                
                return false;
            }
            if (!jTextFieldBDex.getText().equals("0") && ficha.getbDex() != 0) {
                JOptionPane.showMessageDialog(null, "Sua classe já lhe dá bonus de Dex!",
                    "Error!", JOptionPane.ERROR_MESSAGE);
                
                return false;
            }
            if (!jTextFieldBInt.getText().equals("0") && ficha.getbInt() != 0) {
                JOptionPane.showMessageDialog(null, "Sua classe já lhe dá bonus de Int!",
                    "Error!", JOptionPane.ERROR_MESSAGE);
                
                return false;
            }
            if (!jTextFieldBCar.getText().equals("0") && ficha.getbCar() != 0) {
                JOptionPane.showMessageDialog(null, "Sua classe já lhe dá bonus de Car!",
                    "Error!", JOptionPane.ERROR_MESSAGE);
                
                return false;
            }
            if (!jTextFieldBMen.getText().equals("0") && ficha.getbMen() != 0) {
                JOptionPane.showMessageDialog(null, "Sua classe já lhe dá bonus de Men!",
                    "Error!", JOptionPane.ERROR_MESSAGE);
                
                return false;
            }
            
            return true;

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Entre apenas com números inteiros!\n",
                "Error!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    
    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        try {
            Ficha ficha = AlgoritmoPrincipalGerador.getFicha();
            
            // validando distribuição
            if (!validarDistribuicao(ficha)) {
                return;
            }

            // setando bonus da ficha
            ficha.setbCar(ficha.getbCar() + Integer.parseInt(jTextFieldBCar.getText()));
            ficha.setbFor(ficha.getbFor() + Integer.parseInt(jTextFieldBFor.getText()));
            ficha.setbInt(ficha.getbInt() + Integer.parseInt(jTextFieldBInt.getText()));
            ficha.setbDex(ficha.getbDex() + Integer.parseInt(jTextFieldBDex.getText()));
            ficha.setbMen(ficha.getbMen() + Integer.parseInt(jTextFieldBMen.getText()));
            ficha.setbCon(ficha.getbCon() + Integer.parseInt(jTextFieldBCon.getText()));

            this.dispose();
            
        } catch (NumberFormatException e) {
            
        }
    }//GEN-LAST:event_jButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_bonusLivre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            View_bonusLivre dialog = new View_bonusLivre(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelModCar;
    private javax.swing.JLabel jLabelModCon;
    private javax.swing.JLabel jLabelModDex;
    private javax.swing.JLabel jLabelModFor;
    private javax.swing.JLabel jLabelModInt;
    private javax.swing.JLabel jLabelModMen;
    private javax.swing.JLabel jLabelPerCar;
    private javax.swing.JLabel jLabelPerCon;
    private javax.swing.JLabel jLabelPerDex;
    private javax.swing.JLabel jLabelPerFor;
    private javax.swing.JLabel jLabelPerInt;
    private javax.swing.JLabel jLabelPerMen;
    private javax.swing.JLabel jLabelValCar;
    private javax.swing.JLabel jLabelValCon;
    private javax.swing.JLabel jLabelValDex;
    private javax.swing.JLabel jLabelValFor;
    private javax.swing.JLabel jLabelValInt;
    private javax.swing.JLabel jLabelValMen;
    private javax.swing.JLabel jLabelp1;
    private javax.swing.JLabel jLabelp2;
    private javax.swing.JLabel jLabelp3;
    private javax.swing.JLabel jLabelp4;
    private javax.swing.JLabel jLabelp5;
    private javax.swing.JLabel jLabelp6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldBCar;
    private javax.swing.JTextField jTextFieldBCon;
    private javax.swing.JTextField jTextFieldBDex;
    private javax.swing.JTextField jTextFieldBFor;
    private javax.swing.JTextField jTextFieldBInt;
    private javax.swing.JTextField jTextFieldBMen;
    // End of variables declaration//GEN-END:variables
}
