/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.batalhas;

import algoritmos.batalhas.AlgoritmoPrincipal;
import ficha_personagem.Ficha;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 422UR4H
 */
public class ViewFichaMob extends javax.swing.JFrame {

    /**
     * Creates new form ViewFicha
     * @throws java.lang.ClassNotFoundException
     */
    public ViewFichaMob() throws ClassNotFoundException {
        initComponents();
        
        
        // MEU CODIGO
        
        // recebendo ficha
        Ficha ficha = AlgoritmoPrincipal.getFicha(AlgoritmoPrincipal.getLinha());
        
        // setando titulo da ficha
        setTitle(ficha.getNick());
        
        // setando formulario
        jLabelNome.setText(ficha.getNick());
        
        // setando leveis e exps
        jLabelLvl.setText(String.valueOf(ficha.getLvl()));

        // setando valores
        jLabelIni.setText(String.valueOf(ficha.getIni()));
        jLabelEsq.setText(String.valueOf(ficha.getEsq()));
        jLabelHp.setText(String.valueOf(ficha.getHpMax()));
        jLabelVel.setText(String.valueOf(ficha.getVel()));
        jLabelCrt.setText(String.valueOf(20 - ficha.getCrt()));
        jLabelSrt.setText(String.valueOf(ficha.getSorte()) + "/" + String.valueOf(ficha.getSorteDiaria()));
        
        
        // setando atributos fisicos iniciais
        jLabelForIni.setText(String.valueOf(ficha.getIniFor()));
        jLabelConIni.setText(String.valueOf(ficha.getIniCon()));
        jLabelDexIni.setText(String.valueOf(ficha.getIniDex()));
        jLabelIntIni.setText(String.valueOf(ficha.getIniInt()));
        jLabelCarIni.setText(String.valueOf(ficha.getIniCar()));
        jLabelMenIni.setText(String.valueOf(ficha.getIniMen()));
        
        // setando valores de atributos fisicos
        jLabelValFor.setText(String.valueOf(ficha.getValFor()));
        jLabelValCon.setText(String.valueOf(ficha.getValCon()));
        jLabelValDex.setText(String.valueOf(ficha.getValDex()));
        jLabelValInt.setText(String.valueOf(ficha.getValInt()));
        jLabelValCar.setText(String.valueOf(ficha.getValCar()));
        jLabelValMen.setText(String.valueOf(ficha.getValMen()));
        
        // setando modificadores de atributos fisicos
        jLabelModFor.setText(String.valueOf(ficha.getModFor()));
        jLabelModCon.setText(String.valueOf(ficha.getModCon()));
        jLabelModDex.setText(String.valueOf(ficha.getModDex()));
        jLabelModInt.setText(String.valueOf(ficha.getModInt()));
        jLabelModCar.setText(String.valueOf(ficha.getModCar()));
        jLabelModMen.setText(String.valueOf(ficha.getModMen()));
        
        // setando bonus de atributos fisicos
        jLabelBFor.setText(String.valueOf(ficha.getbFor()));
        jLabelBCon.setText(String.valueOf(ficha.getbCon()));
        jLabelBDex.setText(String.valueOf(ficha.getbDex()));
        jLabelBInt.setText(String.valueOf(ficha.getbInt()));
        jLabelBCar.setText(String.valueOf(ficha.getbCar()));
        jLabelBMen.setText(String.valueOf(ficha.getbMen()));
        
        // setando pericias de atributos fisicos
        jLabelPerFor.setText(String.valueOf(ficha.getPerFor()));
        jLabelPerCon.setText(String.valueOf(ficha.getPerCon()));
        jLabelPerDex.setText(String.valueOf(ficha.getPerDex()));
        jLabelPerInt.setText(String.valueOf(ficha.getPerInt()));
        jLabelPerCar.setText(String.valueOf(ficha.getPerCar()));
        jLabelPerMen.setText(String.valueOf(ficha.getPerMen()));
        
        // FIM DO MEU CODIGO
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabelIni = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabelVel = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabelForIni = new javax.swing.JLabel();
        jLabelConIni = new javax.swing.JLabel();
        jLabelDexIni = new javax.swing.JLabel();
        jLabelIntIni = new javax.swing.JLabel();
        jLabelCarIni = new javax.swing.JLabel();
        jLabelMenIni = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabelValCon = new javax.swing.JLabel();
        jLabelValDex = new javax.swing.JLabel();
        jLabelValInt = new javax.swing.JLabel();
        jLabelValCar = new javax.swing.JLabel();
        jLabelValMen = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabelValFor = new javax.swing.JLabel();
        jLabelBMen = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabelBFor = new javax.swing.JLabel();
        jLabelModFor = new javax.swing.JLabel();
        jLabelModCon = new javax.swing.JLabel();
        jLabelModDex = new javax.swing.JLabel();
        jLabelModInt = new javax.swing.JLabel();
        jLabelModCar = new javax.swing.JLabel();
        jLabelModMen = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabelBCon = new javax.swing.JLabel();
        jLabelBDex = new javax.swing.JLabel();
        jLabelBInt = new javax.swing.JLabel();
        jLabelBCar = new javax.swing.JLabel();
        jLabelPerMen = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabelPerFor = new javax.swing.JLabel();
        jLabelPerCon = new javax.swing.JLabel();
        jLabelPerDex = new javax.swing.JLabel();
        jLabelPerInt = new javax.swing.JLabel();
        jLabelPerCar = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabelCrt = new javax.swing.JLabel();
        jLabelEsq = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabelSrt = new javax.swing.JLabel();
        jLabelHp = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabelLvl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ficha");
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        jLabel39.setBackground(new java.awt.Color(51, 51, 51));
        jLabel39.setText("Iniciativa: ");

        jLabelIni.setBackground(new java.awt.Color(0, 255, 0));
        jLabelIni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIni.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel41.setBackground(new java.awt.Color(51, 51, 51));
        jLabel41.setText("Velocidade: ");

        jLabelVel.setBackground(new java.awt.Color(0, 255, 0));
        jLabelVel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel45.setBackground(new java.awt.Color(102, 102, 102));
        jLabel45.setText("For: ");

        jLabel46.setBackground(new java.awt.Color(102, 102, 102));
        jLabel46.setText("Con: ");

        jLabel47.setBackground(new java.awt.Color(102, 102, 102));
        jLabel47.setText("Dex: ");

        jLabel48.setBackground(new java.awt.Color(102, 102, 102));
        jLabel48.setText("Int: ");

        jLabel49.setBackground(new java.awt.Color(102, 102, 102));
        jLabel49.setText("Car: ");

        jLabel50.setBackground(new java.awt.Color(102, 102, 102));
        jLabel50.setText("Men: ");

        jLabel51.setBackground(new java.awt.Color(102, 102, 102));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("ATR");

        jLabelForIni.setBackground(new java.awt.Color(51, 51, 51));
        jLabelForIni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelForIni.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelConIni.setBackground(new java.awt.Color(51, 51, 51));
        jLabelConIni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConIni.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelDexIni.setBackground(new java.awt.Color(51, 51, 51));
        jLabelDexIni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDexIni.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelIntIni.setBackground(new java.awt.Color(51, 51, 51));
        jLabelIntIni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIntIni.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelCarIni.setBackground(new java.awt.Color(51, 51, 51));
        jLabelCarIni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCarIni.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelMenIni.setBackground(new java.awt.Color(51, 51, 51));
        jLabelMenIni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenIni.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel58.setBackground(new java.awt.Color(102, 102, 102));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("INI");

        jLabelValCon.setBackground(new java.awt.Color(0, 255, 255));
        jLabelValCon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelValCon.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelValDex.setBackground(new java.awt.Color(0, 255, 255));
        jLabelValDex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelValDex.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelValInt.setBackground(new java.awt.Color(0, 255, 255));
        jLabelValInt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelValInt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelValCar.setBackground(new java.awt.Color(0, 255, 255));
        jLabelValCar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelValCar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelValMen.setBackground(new java.awt.Color(0, 255, 255));
        jLabelValMen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelValMen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel64.setBackground(new java.awt.Color(102, 102, 102));
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("VAL");

        jLabelValFor.setBackground(new java.awt.Color(0, 255, 255));
        jLabelValFor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelValFor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelBMen.setBackground(new java.awt.Color(51, 51, 51));
        jLabelBMen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBMen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel67.setBackground(new java.awt.Color(102, 102, 102));
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("B.");

        jLabelBFor.setBackground(new java.awt.Color(51, 51, 51));
        jLabelBFor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBFor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelModFor.setBackground(new java.awt.Color(51, 51, 51));
        jLabelModFor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelModFor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelModCon.setBackground(new java.awt.Color(51, 51, 51));
        jLabelModCon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelModCon.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelModDex.setBackground(new java.awt.Color(51, 51, 51));
        jLabelModDex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelModDex.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelModInt.setBackground(new java.awt.Color(51, 51, 51));
        jLabelModInt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelModInt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelModCar.setBackground(new java.awt.Color(51, 51, 51));
        jLabelModCar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelModCar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelModMen.setBackground(new java.awt.Color(51, 51, 51));
        jLabelModMen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelModMen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel75.setBackground(new java.awt.Color(102, 102, 102));
        jLabel75.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel75.setText("MOD");

        jLabelBCon.setBackground(new java.awt.Color(51, 51, 51));
        jLabelBCon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBCon.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelBDex.setBackground(new java.awt.Color(51, 51, 51));
        jLabelBDex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBDex.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelBInt.setBackground(new java.awt.Color(51, 51, 51));
        jLabelBInt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBInt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelBCar.setBackground(new java.awt.Color(51, 51, 51));
        jLabelBCar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBCar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPerMen.setBackground(new java.awt.Color(0, 255, 0));
        jLabelPerMen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPerMen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel81.setBackground(new java.awt.Color(102, 102, 102));
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel81.setText("PER");

        jLabelPerFor.setBackground(new java.awt.Color(0, 255, 0));
        jLabelPerFor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPerFor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPerCon.setBackground(new java.awt.Color(0, 255, 0));
        jLabelPerCon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPerCon.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPerDex.setBackground(new java.awt.Color(0, 255, 0));
        jLabelPerDex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPerDex.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPerInt.setBackground(new java.awt.Color(0, 255, 0));
        jLabelPerInt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPerInt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPerCar.setBackground(new java.awt.Color(0, 255, 0));
        jLabelPerCar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPerCar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel88.setBackground(new java.awt.Color(51, 51, 51));
        jLabel88.setText("Crítico: ");

        jLabel89.setBackground(new java.awt.Color(51, 51, 51));
        jLabel89.setText("Esquiva: ");

        jLabelCrt.setBackground(new java.awt.Color(0, 255, 0));
        jLabelCrt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCrt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelEsq.setBackground(new java.awt.Color(0, 255, 0));
        jLabelEsq.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEsq.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Nome: ");

        jLabelNome.setBackground(new java.awt.Color(51, 51, 51));
        jLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNome.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel32.setBackground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("Sortes: ");

        jLabelSrt.setBackground(new java.awt.Color(51, 51, 51));
        jLabelSrt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSrt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelHp.setBackground(new java.awt.Color(51, 51, 51));
        jLabelHp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHp.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel91.setBackground(new java.awt.Color(51, 51, 51));
        jLabel91.setText("Hp: ");

        jLabel2.setText("Level");

        jLabelLvl.setBackground(new java.awt.Color(51, 51, 51));
        jLabelLvl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLvl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator2)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel51, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel50))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelIntIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelDexIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelConIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelCarIni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelMenIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelForIni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel64, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelValInt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelValDex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelValCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelValCar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelValMen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelValFor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel75, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelModInt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelModDex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelModCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelModCar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelModMen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelModFor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel67, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelBInt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelBDex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelBCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelBCar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelBMen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelBFor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel81, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPerInt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPerDex, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPerCon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPerCar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPerFor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPerMen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelIni, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelVel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel89, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabelSrt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel91, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelHp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelEsq, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelCrt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(11, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabelIni, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabelVel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEsq, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCrt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSrt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel91, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHp, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelForIni, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelConIni, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDexIni, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelIntIni, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCarIni, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMenIni, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelValFor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelValCon, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelValDex, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelValInt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelValCar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelValMen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelModFor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelModCon, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelModDex, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelModInt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelModCar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelModMen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelBFor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelBCon, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelBDex, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelBInt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelBCar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelBMen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPerFor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPerCon, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPerDex, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPerInt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPerCar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPerMen, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFichaMob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFichaMob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFichaMob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFichaMob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new ViewFichaMob().setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ViewFichaMob.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabelBCar;
    private javax.swing.JLabel jLabelBCon;
    private javax.swing.JLabel jLabelBDex;
    private javax.swing.JLabel jLabelBFor;
    private javax.swing.JLabel jLabelBInt;
    private javax.swing.JLabel jLabelBMen;
    private javax.swing.JLabel jLabelCarIni;
    private javax.swing.JLabel jLabelConIni;
    private javax.swing.JLabel jLabelCrt;
    private javax.swing.JLabel jLabelDexIni;
    private javax.swing.JLabel jLabelEsq;
    private javax.swing.JLabel jLabelForIni;
    private javax.swing.JLabel jLabelHp;
    private javax.swing.JLabel jLabelIni;
    private javax.swing.JLabel jLabelIntIni;
    private javax.swing.JLabel jLabelLvl;
    private javax.swing.JLabel jLabelMenIni;
    private javax.swing.JLabel jLabelModCar;
    private javax.swing.JLabel jLabelModCon;
    private javax.swing.JLabel jLabelModDex;
    private javax.swing.JLabel jLabelModFor;
    private javax.swing.JLabel jLabelModInt;
    private javax.swing.JLabel jLabelModMen;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPerCar;
    private javax.swing.JLabel jLabelPerCon;
    private javax.swing.JLabel jLabelPerDex;
    private javax.swing.JLabel jLabelPerFor;
    private javax.swing.JLabel jLabelPerInt;
    private javax.swing.JLabel jLabelPerMen;
    private javax.swing.JLabel jLabelSrt;
    private javax.swing.JLabel jLabelValCar;
    private javax.swing.JLabel jLabelValCon;
    private javax.swing.JLabel jLabelValDex;
    private javax.swing.JLabel jLabelValFor;
    private javax.swing.JLabel jLabelValInt;
    private javax.swing.JLabel jLabelValMen;
    private javax.swing.JLabel jLabelVel;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
