/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.batalhas;

import algoritmos.batalhas.AlgoritmoPrincipal;
import algoritmos.batalhas.Calculadora;
import ficha_personagem.Ficha;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author 422UR4H
 */
public class View_stun extends javax.swing.JDialog {

    /**
     * Creates new form View_stun
     * @param parent
     * @param modal
     */
    public View_stun(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        // MEU CODIGO AQUI
        
        Ficha personagem = AlgoritmoPrincipal.getFicha();
        int stunAtual = personagem.getStun();
        int danoRecebido = Calculadora.getDano_stun();
        int cdDoTeste = stunAtual + danoRecebido;
        
        jLabelPersonagem.setText(personagem.getNick());
        jLabelStunAtual.setText(String.valueOf(stunAtual));
        jLabelDanoRecebido.setText(String.valueOf(danoRecebido));
        jLabelPericiaDeCon.setText(String.valueOf(personagem.getPerCon()));
        jLabelCdDoTeste.setText(String.valueOf(cdDoTeste));
        
        // FIM DO MEU CODIGO AQUI
    }

    private void atualizarLabels(int stunAtual) {
        int cdDoTeste = stunAtual + Integer.parseInt(jLabelDanoRecebido.getText());;
        
        jLabelStunAtual.setText(String.valueOf(stunAtual));
        jLabelCdDoTeste.setText(String.valueOf(cdDoTeste));
    }
    
    private void aplicarStun() {
        int dado;
        try {
            dado = Integer.parseInt(jTextFieldValorDoDado.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Entre com um valor inteiro válido",
                    "Error!", JOptionPane.ERROR_MESSAGE);
            
            return;
        }
        if (dado < 1 || dado > 20) {
            JOptionPane.showMessageDialog(null, "O valor do dado deve ser entre 1 e 20!",
                    "Logic Error!", JOptionPane.ERROR_MESSAGE);
            
            return;
        }
        
        Ficha personagem = AlgoritmoPrincipal.getPerson(jLabelPersonagem.getText());
        int danoRecebido = Integer.parseInt(jLabelDanoRecebido.getText());
        int stunAtual = personagem.getStun();
        int pericia = personagem.getPerCon();
        int teste = Calculadora.getTeste(dado, pericia);
        int restoDoDano = danoRecebido - teste;
        
        if (restoDoDano > 0) {
            personagem.addStun(restoDoDano);
        } else if (stunAtual > 0) { // só reduz stun se o defensor estiver stunado
            personagem.reduzStun(restoDoDano);
            if (personagem.getStun() == 0) {
                
                JOptionPane.showMessageDialog(null, 
                        personagem.getNick() + " não está mais stunado!");
            
            }
        }
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButtonAplicarStun = new javax.swing.JButton();
        jLabelDanoRecebido = new javax.swing.JLabel();
        jButtonCancelarStun = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelPericiaDeCon = new javax.swing.JLabel();
        jLabelPersonagem = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelStunAtual = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelCdDoTeste = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldValorDoDado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stun");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel12.setText("Dano Recebido:");

        jButtonAplicarStun.setBackground(new java.awt.Color(102, 102, 102));
        jButtonAplicarStun.setText("Aplicar");
        jButtonAplicarStun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAplicarStunActionPerformed(evt);
            }
        });

        jButtonCancelarStun.setBackground(new java.awt.Color(102, 102, 102));
        jButtonCancelarStun.setText("Cancelar");
        jButtonCancelarStun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarStunActionPerformed(evt);
            }
        });

        jLabel14.setText("Pericia de Con:");

        jLabel1.setText("Personagem: ");

        jLabel10.setText("Stun Atual:");

        jLabel16.setText("CD do Teste:");

        jLabel18.setText("Valor do Dado:");

        jTextFieldValorDoDado.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldValorDoDado.setForeground(new java.awt.Color(0, 255, 0));
        jTextFieldValorDoDado.setCaretColor(new java.awt.Color(0, 255, 0));
        jTextFieldValorDoDado.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldValorDoDado.setSelectionColor(new java.awt.Color(0, 255, 255));
        jTextFieldValorDoDado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldValorDoDadoFocusGained(evt);
            }
        });
        jTextFieldValorDoDado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldValorDoDadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextFieldValorDoDadoMouseEntered(evt);
            }
        });
        jTextFieldValorDoDado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldValorDoDadoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabelPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabelPericiaDeCon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAplicarStun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCancelarStun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldValorDoDado)
                            .addComponent(jLabelCdDoTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelStunAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDanoRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStunAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDanoRecebido, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPericiaDeCon, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCdDoTeste, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldValorDoDado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAplicarStun)
                    .addComponent(jButtonCancelarStun))
                .addGap(11, 11, 11))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAplicarStunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAplicarStunActionPerformed
        aplicarStun();
    }//GEN-LAST:event_jButtonAplicarStunActionPerformed

    private void jButtonCancelarStunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarStunActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarStunActionPerformed

    private void jTextFieldValorDoDadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldValorDoDadoFocusGained
        Ficha personagem = AlgoritmoPrincipal.getPerson(jLabelPersonagem.getText());
        atualizarLabels(personagem.getStun());
    }//GEN-LAST:event_jTextFieldValorDoDadoFocusGained

    private void jTextFieldValorDoDadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldValorDoDadoMouseClicked
        jTextFieldValorDoDado.selectAll();
    }//GEN-LAST:event_jTextFieldValorDoDadoMouseClicked

    private void jTextFieldValorDoDadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldValorDoDadoMouseEntered
        jTextFieldValorDoDado.setToolTipText("Valor do dado puro do teste do jogador");
    }//GEN-LAST:event_jTextFieldValorDoDadoMouseEntered

    private void jTextFieldValorDoDadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldValorDoDadoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            aplicarStun();
        }
        
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jTextFieldValorDoDadoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_stun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_stun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_stun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_stun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            View_stun dialog = new View_stun(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAplicarStun;
    private javax.swing.JButton jButtonCancelarStun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabelCdDoTeste;
    private javax.swing.JLabel jLabelDanoRecebido;
    private javax.swing.JLabel jLabelPericiaDeCon;
    private javax.swing.JLabel jLabelPersonagem;
    private javax.swing.JLabel jLabelStunAtual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldValorDoDado;
    // End of variables declaration//GEN-END:variables
}
