
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.batalhas;

import algoritmos.batalhas.AlgoritmoPrincipal;
import ficha_personagem.Ficha;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author 422UR4H
 */
public class View_operarValor extends javax.swing.JDialog {

    /**
     * Creates new form View_editarValor
     * @param parent
     * @param modal
     */
    public View_operarValor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        // MEU CODIGO
        
        // se o usuario quiser editar o mop
        if (AlgoritmoPrincipal.getLinha().equals(AlgoritmoPrincipal.getMOP())) {
        
            jLabelPersonagem.setText(AlgoritmoPrincipal.getFicha().getNick());
            jLabelInfoAtual.setText("MOP Atual:");
            jLabelValorAtual.setText(String.valueOf(AlgoritmoPrincipal.getFicha().getMopAtual()));
            jLabelNovoValor.setText("Novo valor de MOP:");
        
        } else { // hp
            
            jLabelPersonagem.setText(AlgoritmoPrincipal.getFicha().getNick());
            jLabelInfoAtual.setText("HP Atual:");
            jLabelValorAtual.setText(String.valueOf(AlgoritmoPrincipal.getFicha().getHpAtual()));
            jLabelNovoValor.setText("Novo valor de HP:");
        
        }
        
        // FIM DO MEU CODIGO
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonAplicar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelPersonagem = new javax.swing.JLabel();
        jLabelInfoAtual = new javax.swing.JLabel();
        jLabelValorAtual = new javax.swing.JLabel();
        jLabelNovoValor = new javax.swing.JLabel();
        jTextFieldEditarValor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stun");
        setResizable(false);

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jButtonAplicar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonAplicar.setText("Aplicar");
        jButtonAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAplicarActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Personagem: ");

        jLabelInfoAtual.setText("MOP Atual:");

        jLabelNovoValor.setText("Operar valor de MOP: ");

        jTextFieldEditarValor.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldEditarValor.setForeground(new java.awt.Color(0, 255, 0));
        jTextFieldEditarValor.setText("+");
        jTextFieldEditarValor.setCaretColor(new java.awt.Color(0, 255, 0));
        jTextFieldEditarValor.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldEditarValor.setSelectionColor(new java.awt.Color(0, 255, 255));
        jTextFieldEditarValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEditarValorFocusGained(evt);
            }
        });
        jTextFieldEditarValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEditarValorKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNovoValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelInfoAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelPersonagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelValorAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEditarValor)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jButtonCancelar)))
                .addGap(6, 6, 6))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelPersonagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelValorAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelInfoAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldEditarValor)
                    .addComponent(jLabelNovoValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAplicar)
                    .addComponent(jButtonCancelar))
                .addGap(6, 6, 6))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aplicar() {
        try {
            Ficha personagem = AlgoritmoPrincipal.getFicha();
            
            // se o usuario quiser editar o mop
            if (AlgoritmoPrincipal.getLinha().equals(AlgoritmoPrincipal.getMOP())) {
                
                int mop = personagem.getMopAtual();
                mop += Integer.parseInt(jTextFieldEditarValor.getText());
                
                if (mop > personagem.getMopMax()) {
                    mop = personagem.getMopMax();
                }
                personagem.setMopAtual(mop);
                
            } else { // hp
                
                int hp = personagem.getHpAtual();
                hp += Integer.parseInt(jTextFieldEditarValor.getText());
                
                if (hp > personagem.getHpMax()) {
                    hp = personagem.getHpMax();
                }
                personagem.setHpAtual(hp);
                
                if (personagem.isDesmaiado()) {
                    
                    switch (JOptionPane.showConfirmDialog(null, "Acordar personagem do desmaio?",
                        "Faint", JOptionPane.YES_NO_OPTION)) {
                        
                        case 0:
                        personagem.setDesmaiado(false);
                        break;
                    }
                    
                } else if (personagem.getHpAtual() < 0) {

                    switch (JOptionPane.showConfirmDialog(null, "Desmaiar personagem?",
                        "Faint", JOptionPane.YES_NO_OPTION)) {
                    case 0:
                        personagem.setDesmaiado(true);
                        break;
                    }
                }
                
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Entre com um valor inteiro válido",
                    "Error!", JOptionPane.ERROR_MESSAGE);
            
            return;
        }

        this.dispose();
    }
    
    private void jButtonAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAplicarActionPerformed
        aplicar();
    }//GEN-LAST:event_jButtonAplicarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldEditarValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEditarValorFocusGained
        jTextFieldEditarValor.selectAll();
    }//GEN-LAST:event_jTextFieldEditarValorFocusGained

    private void jTextFieldEditarValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEditarValorKeyPressed
        // se o usuario quiser editar o mop
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            aplicar();
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_jTextFieldEditarValorKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_operarValor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            View_operarValor dialog = new View_operarValor(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAplicar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelInfoAtual;
    private javax.swing.JLabel jLabelNovoValor;
    private javax.swing.JLabel jLabelPersonagem;
    private javax.swing.JLabel jLabelValorAtual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldEditarValor;
    // End of variables declaration//GEN-END:variables
}
