/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.trainer;

import algoritmos.trainer.AlgoritmoPrincipalTrainer;
import algoritmos.trainer.CalculadoraTrainer;
import ficha_personagem.Ficha;
import ficha_personagem.LvlExp;
import ficha_personagem.Treino;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 422UR4H
 */
public class View_treinoNen extends javax.swing.JDialog {

    /** Creates new form View_treinoNen
     * @param parent
     * @param modal */
    public View_treinoNen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
        // MEU CODIGO
        
        // setando nome da pericia ou proficiencia
        jLabelNome.setText(AlgoritmoPrincipalTrainer.getNomeTreino());
        
        // desabilitando jButtons
        desabilitandoCampos();
        
        // habilitando mensagens de up ao usuario
        jCheckBoxMenuItemOcultMessages.setSelected(false);
        
        // setando lvlBonus para facilitar a manipulação de valores
        LvlExp lvlExp = new LvlExp();
        Ficha ficha = AlgoritmoPrincipalTrainer.getFicha();
        String nome = AlgoritmoPrincipalTrainer.getNomeTreino();

        lvlExp.setLvl(ficha.getAtr(nome).getLvl());
        lvlExp.setExp(ficha.getAtr(nome).getExp());
        
        // setando informações de lvl e exp
        jLabelLvlInicial.setText(String.valueOf(lvlExp.getLvl()));
        jLabelLvlAtual.setText(String.valueOf(lvlExp.getLvl()));
        jLabelExpInicial.setText(String.valueOf(lvlExp.getExp()));
        jLabelLevel.setText(String.valueOf(ficha.getLvl()));
        jLabelNen.setText(String.valueOf(ficha.getLvlNen()));
        
        // iniciando jProgressBars
        // valores maximos
        if (AlgoritmoPrincipalTrainer.getNomeTreino().equals("MOP")) {
            jProgressBarLvlAtual.setMaximum(CalculadoraTrainer.getExpMop(lvlExp.getLvl() + 1));
        } else {
            jProgressBarLvlAtual.setMaximum(AlgoritmoPrincipalTrainer.getEXP_NEN(lvlExp.getLvl() + 1));
        }
        jProgressBarLevel.setMaximum(AlgoritmoPrincipalTrainer.getEXP_LVL(ficha.getLvl() + 1));
        jProgressBarNen.setMaximum(AlgoritmoPrincipalTrainer.getLVL_NEN(ficha.getLvlNen() + 1));
        // valores atuais
        jProgressBarLvlAtual.setValue(lvlExp.getExp());
        jProgressBarLevel.setValue(ficha.getExp());
        jProgressBarNen.setValue(ficha.getExpNen());
        
        // setando perícia
        setPericia();
        
        double diasIgnorados = AlgoritmoPrincipalTrainer.getDiasIgnorados();
        if (diasIgnorados != 0) {
            jTextFieldQtd.setText(String.valueOf(2 * diasIgnorados));
            jTextFieldQtd.setEnabled(false);
            jButtonQtdOk.setEnabled(false);
            
            initTreino();
        }
        
        // FIM DO MEU CODIGO
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabelDado = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelPer = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelLvlInicial = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelExpInicial = new javax.swing.JLabel();
        jTextFieldQtd = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButtonQtdOk = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jCheckBoxAteUpar = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelLvlAtual = new javax.swing.JLabel();
        jLabelDadosJogados = new javax.swing.JLabel();
        jLabelDadosRestantes = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldDado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButtonDadoOk = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButtonFechar = new javax.swing.JButton();
        jProgressBarLvlAtual = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabelLevel = new javax.swing.JLabel();
        jProgressBarLevel = new javax.swing.JProgressBar();
        jProgressBarNen = new javax.swing.JProgressBar();
        jLabelNen = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItemOcultMessages = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Treino Nen");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jTable.setBackground(new java.awt.Color(51, 51, 51));
        jTable.setForeground(new java.awt.Color(0, 255, 0));
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Treino", "Rolagem", "Experiência"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.setSelectionBackground(new java.awt.Color(0, 255, 255));
        jTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(jTable);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabelDado.setBackground(new java.awt.Color(102, 102, 102));
        jLabelDado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("+");

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Per");

        jLabelPer.setBackground(new java.awt.Color(102, 102, 102));
        jLabelPer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("=");

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Total");

        jLabelTotal.setBackground(new java.awt.Color(102, 102, 102));
        jLabelTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Exp Inicial: ");

        jLabel16.setBackground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Lvl Inicial: ");

        jLabelLvlInicial.setBackground(new java.awt.Color(102, 102, 102));
        jLabelLvlInicial.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Treinar quantas vezes?");

        jLabelExpInicial.setBackground(new java.awt.Color(102, 102, 102));
        jLabelExpInicial.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldQtd.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldQtd.setForeground(new java.awt.Color(0, 255, 0));
        jTextFieldQtd.setCaretColor(new java.awt.Color(0, 255, 0));
        jTextFieldQtd.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldQtd.setSelectionColor(new java.awt.Color(0, 255, 255));
        jTextFieldQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldQtdKeyPressed(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Treino: ");

        jButtonQtdOk.setBackground(new java.awt.Color(102, 102, 102));
        jButtonQtdOk.setText("OK");
        jButtonQtdOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQtdOkActionPerformed(evt);
            }
        });

        jLabelNome.setBackground(new java.awt.Color(102, 102, 102));

        jCheckBoxAteUpar.setBackground(new java.awt.Color(102, 102, 102));
        jCheckBoxAteUpar.setText("Até Upar");

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Dados Jogados: ");

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Dados Restantes: ");

        jLabelLvlAtual.setBackground(new java.awt.Color(102, 102, 102));
        jLabelLvlAtual.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelDadosJogados.setBackground(new java.awt.Color(102, 102, 102));
        jLabelDadosJogados.setText("0");

        jLabelDadosRestantes.setBackground(new java.awt.Color(102, 102, 102));

        jLabel22.setBackground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Lvl Atual: ");

        jTextFieldDado.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldDado.setForeground(new java.awt.Color(0, 255, 0));
        jTextFieldDado.setCaretColor(new java.awt.Color(0, 255, 0));
        jTextFieldDado.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDado.setSelectionColor(new java.awt.Color(0, 255, 255));
        jTextFieldDado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDadoFocusGained(evt);
            }
        });
        jTextFieldDado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDadoKeyPressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Dado: ");

        jButtonDadoOk.setBackground(new java.awt.Color(102, 102, 102));
        jButtonDadoOk.setText("OK");
        jButtonDadoOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDadoOkActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Dado");

        jButtonFechar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonFechar.setText("FECHAR");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jProgressBarLvlAtual.setForeground(new java.awt.Color(0, 255, 0));
        jProgressBarLvlAtual.setString("");
        jProgressBarLvlAtual.setStringPainted(true);
        jProgressBarLvlAtual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jProgressBarLvlAtualMouseEntered(evt);
            }
        });

        jLabel4.setText("Level: ");

        jLabelLevel.setBackground(new java.awt.Color(102, 102, 102));
        jLabelLevel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jProgressBarLevel.setForeground(new java.awt.Color(255, 0, 0));
        jProgressBarLevel.setString("");
        jProgressBarLevel.setStringPainted(true);
        jProgressBarLevel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jProgressBarLevelMouseEntered(evt);
            }
        });

        jProgressBarNen.setForeground(new java.awt.Color(255, 0, 0));
        jProgressBarNen.setString("");
        jProgressBarNen.setStringPainted(true);
        jProgressBarNen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jProgressBarNenMouseEntered(evt);
            }
        });

        jLabelNen.setBackground(new java.awt.Color(102, 102, 102));
        jLabelNen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Nen: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBarNen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jProgressBarLevel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jProgressBarLvlAtual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDadoOk))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDadosJogados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDadosRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jCheckBoxAteUpar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldQtd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonQtdOk))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelExpInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelLvlAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelPer, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLvlInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonQtdOk, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxAteUpar)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDadosJogados, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDadosRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonDadoOk)
                        .addComponent(jTextFieldDado))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDado, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPer, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLvlInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelExpInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLvlAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jProgressBarLvlAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabelLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jProgressBarLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabelNen, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jProgressBarNen, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonFechar)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Mensagens");

        jCheckBoxMenuItemOcultMessages.setSelected(true);
        jCheckBoxMenuItemOcultMessages.setText("Desativar Mensagens de Up");
        jMenu1.add(jCheckBoxMenuItemOcultMessages);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void setPericia() {
        Ficha ficha = AlgoritmoPrincipalTrainer.getFicha();
        
        switch (AlgoritmoPrincipalTrainer.getNomeTreino()) {
            case "AOP":
                CalculadoraTrainer.setModClas(1.0);
                AlgoritmoPrincipalTrainer.setPericia(ficha.getPerFor());
                jLabelPer.setText(String.valueOf(ficha.getPerFor()));
                break;
            case "MOP":
                CalculadoraTrainer.setModClas(1.0);
                AlgoritmoPrincipalTrainer.setPericia(ficha.getPerCon());
                jLabelPer.setText(String.valueOf(ficha.getPerCon()));
                break;
            case "RYU":
                CalculadoraTrainer.setModClas(1.0);
                AlgoritmoPrincipalTrainer.setPericia(ficha.getPerCdn());
                jLabelPer.setText(String.valueOf(ficha.getPerCdn()));
                break;
            case "REF":
                switch (AlgoritmoPrincipalTrainer.getNome()) {
                    case "Reforco":
                        CalculadoraTrainer.setModClas(1.0);
                        break;
                    case "Emissao":
                        CalculadoraTrainer.setModClas(0.8);
                        break;
                    case "Manipulacao":
                        CalculadoraTrainer.setModClas(0.6);
                        break;
                    case "Materializacao":
                        CalculadoraTrainer.setModClas(0.6);
                        break;
                    case "Transformacao":
                        CalculadoraTrainer.setModClas(0.8);
                        break;
                    case "Especializacao":
                        CalculadoraTrainer.setModClas(0.4);
                        break;
                }
                AlgoritmoPrincipalTrainer.setPericia(ficha.getPerInt());
                jLabelPer.setText(String.valueOf(ficha.getPerInt()));
                break;
            case "EMS":
                switch (AlgoritmoPrincipalTrainer.getNome()) {
                    case "Reforco":
                        CalculadoraTrainer.setModClas(0.8);
                        break;
                    case "Emissao":
                        CalculadoraTrainer.setModClas(1.0);
                        break;
                    case "Manipulacao":
                        CalculadoraTrainer.setModClas(0.8);
                        break;
                    case "Materializacao":
                        CalculadoraTrainer.setModClas(0.4);
                        break;
                    case "Transformacao":
                        CalculadoraTrainer.setModClas(0.6);
                        break;
                    case "Especialista":
                        CalculadoraTrainer.setModClas(0.6);
                        break;
                }
                AlgoritmoPrincipalTrainer.setPericia(ficha.getPerInt());
                jLabelPer.setText(String.valueOf(ficha.getPerInt()));
                break;
            case "TRS":
                switch (AlgoritmoPrincipalTrainer.getNome()) {
                    case "Reforco":
                        CalculadoraTrainer.setModClas(0.8);
                        break;
                    case "Emissao":
                        CalculadoraTrainer.setModClas(0.6);
                        break;
                    case "Manipulacao":
                        CalculadoraTrainer.setModClas(0.4);
                        break;
                    case "Materializacao":
                        CalculadoraTrainer.setModClas(0.8);
                        break;
                    case "Transformacao":
                        CalculadoraTrainer.setModClas(1.0);
                        break;
                    case "Especialista":
                        CalculadoraTrainer.setModClas(0.6);
                        break;
                }
                AlgoritmoPrincipalTrainer.setPericia(ficha.getPerInt());
                jLabelPer.setText(String.valueOf(ficha.getPerInt()));
                break;
            case "MAN":
                switch (AlgoritmoPrincipalTrainer.getNome()) {
                    case "Reforco":
                        CalculadoraTrainer.setModClas(0.6);
                        break;
                    case "Emissao":
                        CalculadoraTrainer.setModClas(0.8);
                        break;
                    case "Manipulacao":
                        CalculadoraTrainer.setModClas(1.0);
                        break;
                    case "Materializacao":
                        CalculadoraTrainer.setModClas(0.6);
                        break;
                    case "Transformacao":
                        CalculadoraTrainer.setModClas(0.4);
                        break;
                    case "Especialista":
                        CalculadoraTrainer.setModClas(0.8);
                        break;
                }
                AlgoritmoPrincipalTrainer.setPericia(ficha.getPerInt());
                jLabelPer.setText(String.valueOf(ficha.getPerInt()));
                break;
            case "MAT":
                switch (AlgoritmoPrincipalTrainer.getNome()) {
                    case "Reforco":
                        CalculadoraTrainer.setModClas(0.6);
                        break;
                    case "Emissao":
                        CalculadoraTrainer.setModClas(0.4);
                        break;
                    case "Manipulacao":
                        CalculadoraTrainer.setModClas(0.6);
                        break;
                    case "Materializacao":
                        CalculadoraTrainer.setModClas(1.0);
                        break;
                    case "Transformacao":
                        CalculadoraTrainer.setModClas(0.8);
                        break;
                    case "Especialista":
                        CalculadoraTrainer.setModClas(0.8);
                        break;
                }
                AlgoritmoPrincipalTrainer.setPericia(ficha.getPerInt());
                jLabelPer.setText(String.valueOf(ficha.getPerInt()));
                break;
            case "ESP":
                switch (AlgoritmoPrincipalTrainer.getNome()) {
                    case "Reforco":
                        CalculadoraTrainer.setModClas(0.4);
                        break;
                    case "Emissao":
                        CalculadoraTrainer.setModClas(0.6);
                        break;
                    case "Manipulacao":
                        CalculadoraTrainer.setModClas(0.8);
                        break;
                    case "Materializacao":
                        CalculadoraTrainer.setModClas(0.8);
                        break;
                    case "Transformacao":
                        CalculadoraTrainer.setModClas(0.6);
                        break;
                    case "Especialista":
                        CalculadoraTrainer.setModClas(1.0);
                        break;
                }
                AlgoritmoPrincipalTrainer.setPericia(ficha.getPerInt());
                jLabelPer.setText(String.valueOf(ficha.getPerInt()));
                break;
            default:
                CalculadoraTrainer.setModClas(1.0);
                AlgoritmoPrincipalTrainer.setPericia(ficha.getPerInt());
                jLabelPer.setText(String.valueOf(ficha.getPerInt()));
                break;
        }
    }

    private void desabilitandoCampos() {
        jButtonDadoOk.setEnabled(false);
        jTextFieldDado.setEnabled(false);
    }
    public void setQtdTreinos() {
        double qtd;
        try {
            qtd = Double.parseDouble(jTextFieldQtd.getText());
        } catch (NumberFormatException e) {
            jTextFieldQtd.selectAll();
            return;
        }
        // testado se a qtd de dias setada passa dos limites
        /*if (qtd > 90.0) {
            JOptionPane.showMessageDialog(null, "Você só pode treinar 90 dias por vêz!",
                    "Error!", JOptionPane.WARNING_MESSAGE);
            
            return;
        }*/
        // testando se a quantidade de dias setada faz sentido com a qtd de dias restantes de treino e
        // testando se a quantidade de dias setada é positiva
        if (AlgoritmoPrincipalTrainer.isDiasRestantesSetados()) {
            if ( (qtd / 2.0) > AlgoritmoPrincipalTrainer.getDiasRestantes() || qtd < 0) {
                JOptionPane.showMessageDialog(null, "A quantidade de dados de treino deve ser positiva e\n" +
                        "menor que a quantidade máxima de dias de treino", "Logic Error!", JOptionPane.ERROR_MESSAGE);
                
                jTextFieldQtd.selectAll();
                return;
            }
        }
        
        initTreino();
    }
    
    private void initTreino() {
        double qtd = Double.parseDouble(jTextFieldQtd.getText());
        
        // setando dados restantes
        jLabelDadosRestantes.setText(String.valueOf((int) Double.parseDouble(jTextFieldQtd.getText())));
        AlgoritmoPrincipalTrainer.setSubDiasRestantes(qtd / 2.0);
        
        // desabilitando campos
        jButtonQtdOk.setEnabled(false);
        jTextFieldQtd.setEnabled(false);
        
        // habilitando campos
        jTextFieldDado.setEnabled(true);
        jButtonDadoOk.setEnabled(true);
    }
    
    
    private void upgradeNen(LvlExp lvlExp) {
        // mensagem de upgrade ao usuário
        if (!jCheckBoxMenuItemOcultMessages.isSelected()){
            JOptionPane.showMessageDialog(null, "Seu atributo de nen subiu!",
                    "Congratulations!", JOptionPane.INFORMATION_MESSAGE);
        }

        // setando novo lvl na jLabelLvlAtual
        jLabelLvlAtual.setText(String.valueOf(lvlExp.getLvl()));

        if (jCheckBoxAteUpar.isSelected()) {
            // desabilitando campos
            desabilitandoCampos();
        }
    }
    
    private void upgradeLvl() {
        // mensagem de upgrade ao usuário
        JOptionPane.showMessageDialog(null, "Seu personagem subiu de nível!",
                "Congratulations!", JOptionPane.INFORMATION_MESSAGE);
        
        // abrindo ViewDistribuir
        new View_distribuir(null, true).setVisible(true);
        
        // setando jLabelLevel
        jLabelLevel.setText(String.valueOf(AlgoritmoPrincipalTrainer.getFicha().getLvl()));
        
        // setando pericia
        setPericia();
    }
    
    public void calculaExp() {
        int dado;
        
        // testando valor valido do dado
        try {
            dado = Integer.parseInt(jTextFieldDado.getText());
        } catch (NumberFormatException e) {
            return;
        }
        if (dado < 1 || dado > 20) {
            JOptionPane.showMessageDialog(null, "Entre com um valor do D20!",
                    "Logic Error!", JOptionPane.ERROR_MESSAGE);
            
            jTextFieldDado.setText("");
            return;
        }
        
        
        Ficha ficha = AlgoritmoPrincipalTrainer.getFicha();
        LvlExp lvlExp = ficha.getAtr(AlgoritmoPrincipalTrainer.getNomeTreino());
        
        // incrementando meio dia
        if (AlgoritmoPrincipalTrainer.getDiasIgnorados() == 0) {
            if (AlgoritmoPrincipalTrainer.isDiasRestantesSetados()) {
                AlgoritmoPrincipalTrainer.decrementaMeioDiaRestante();
            }
            AlgoritmoPrincipalTrainer.incrementaMeioDiaTreinado();
            ficha.incrementaMeioDia();
        }
        
        // setando nas jLabels
        // incrementando dados jogados
        jLabelDadosJogados.setText(String.valueOf(Integer.parseInt(jLabelDadosJogados.getText()) + 1));
        // decrementando dados restantes
        jLabelDadosRestantes.setText(String.valueOf((int) Double.parseDouble(jLabelDadosRestantes.getText()) - 1));
        // setando valor do dado
        jLabelDado.setText(String.valueOf(dado));
        // setando valor total
        int exp = (int) ((dado + AlgoritmoPrincipalTrainer.getPericia()) * ((double) ficha.getExpBonus() / 100.0 + 1.0));
        // multiplicando exp por 2, caso 20 natural
        if (dado == 20) {
            exp *= 2;
        }
        jLabelTotal.setText(String.valueOf(exp));
        
        // calculando exp
        // testando se lvlExp é MOP
        if (AlgoritmoPrincipalTrainer.getNomeTreino().equals("MOP")) {
            // CalculadoraUpper.putExpMop retorna true se o atributo upar e false se não upar
            if (CalculadoraTrainer.putExpMop(exp, lvlExp)) {
                jProgressBarLvlAtual.setMaximum(CalculadoraTrainer.getExpMop(lvlExp.getLvl() + 1));
                jProgressBarLvlAtual.setValue(lvlExp.getExp());
                upgradeNen(lvlExp);
                
                // incrementando exp do up na ficha
                // CalculadoraUpper.putExpFicha retorna true se a ficha upar e false se não upar
                if (CalculadoraTrainer.putExpFicha(lvlExp.getLvl() * 10 + 80, ficha)) {
                    jProgressBarLevel.setMaximum(AlgoritmoPrincipalTrainer.getEXP_LVL(ficha.getLvl() + 1));
                    jProgressBarLevel.setValue(ficha.getExp());
                    upgradeLvl();
                } else { // mesmo se o personagem nao upar, sua jProgressBar ganha exp
                    jProgressBarLevel.setValue(ficha.getExp());
                }

                // incrementando exp em exp nen
                CalculadoraTrainer.putExpLvlNen(lvlExp.getLvl() * 10 + 80, ficha);
                jLabelNen.setText(String.valueOf(ficha.getLvlNen()));
                jProgressBarNen.setValue(ficha.getExpNen());
                
                // atualizando mop
                ficha.setMopAtual(ficha.getMop() * 1000);
                ficha.setMopMax(ficha.getMop() * 1000);
            } else { // mesmo se o atributo não upar, a jProgressBar ganha exp
                jProgressBarLvlAtual.setValue(lvlExp.getExp());
            }
        } else {
            // CalculadoraUpper.putExpNen retorna true se o atributo upar e false se não upar
            if (CalculadoraTrainer.putExpNen(exp, lvlExp)) {
                jProgressBarLvlAtual.setMaximum(AlgoritmoPrincipalTrainer.getEXP_NEN(lvlExp.getLvl() + 1));
                jProgressBarLvlAtual.setValue(lvlExp.getExp());
                upgradeNen(lvlExp);
                
                // incrementando exp do up na ficha
                // CalculadoraUpper.putExpFicha retorna true se a ficha upar e false se não upar
                if (CalculadoraTrainer.putExpFicha(AlgoritmoPrincipalTrainer.getEXP_NEN(lvlExp.getLvl()), ficha)) {
                    jProgressBarLevel.setMaximum(AlgoritmoPrincipalTrainer.getEXP_LVL(ficha.getLvl() + 1));
                    jProgressBarLevel.setValue(ficha.getExp());
                    upgradeLvl();
                } else { // mesmo se o personagem nao upar, sua jProgressBar ganha exp
                    jProgressBarLevel.setValue(ficha.getExp());
                }

                // incrementando exp em exp nen
                CalculadoraTrainer.putExpLvlNen(AlgoritmoPrincipalTrainer.getEXP_NEN(lvlExp.getLvl()), ficha);
                jLabelNen.setText(String.valueOf(ficha.getLvlNen()));
                jProgressBarNen.setValue(ficha.getExpNen());
            } else { // mesmo se o atributo não upar, a jProgressBar ganha exp
                jProgressBarLvlAtual.setValue(lvlExp.getExp());
            }
        }
        
        // testando caso do 20
        if (dado == 20 && lvlExp.getLvl() < 40) {
            // incrementando lvl
            lvlExp.incrementaLvl();
            
            // zerando exp
            lvlExp.setExp(0);
            
            // enviando mensagem ao usuario, *desbilitando campos e setanto lvl na label
            jProgressBarLvlAtual.setValue(0);
            upgradeNen(lvlExp);
            
            // incrementando exp do up na ficha
            // testando se lvlExp é MOP
            if (AlgoritmoPrincipalTrainer.getNomeTreino().equals("MOP")) {
                jProgressBarLvlAtual.setMaximum(CalculadoraTrainer.getExpMop(lvlExp.getLvl() + 1));
                // CalculadoraUpper.putExpFicha retorna true se a ficha upar e false se não upar
                if (CalculadoraTrainer.putExpFicha(lvlExp.getLvl() * 10 + 80, ficha)) {
                    jProgressBarLevel.setMaximum(AlgoritmoPrincipalTrainer.getEXP_LVL(ficha.getLvl() + 1));
                    jProgressBarLevel.setValue(ficha.getExp());
                    upgradeLvl();
                } else { // mesmo se o personagem nao upar, sua jProgressBar ganha exp
                    jProgressBarLevel.setValue(ficha.getExp());
                }
                
                // atualizando mop
                ficha.setMopAtual(ficha.getMop() * 1000);
                ficha.setMopMax(ficha.getMop() * 1000);
            } else {
                jProgressBarLvlAtual.setMaximum(AlgoritmoPrincipalTrainer.getEXP_NEN(lvlExp.getLvl() + 1));
                // CalculadoraUpper.putExpFicha retorna true se a ficha upar e false se não upar
                if (CalculadoraTrainer.putExpFicha(AlgoritmoPrincipalTrainer.getEXP_NEN(lvlExp.getLvl()), ficha)) {
                    jProgressBarLevel.setMaximum(AlgoritmoPrincipalTrainer.getEXP_LVL(ficha.getLvl() + 1));
                    jProgressBarLevel.setValue(ficha.getExp());
                    upgradeLvl();
                } else { // mesmo se o personagem nao upar, sua jProgressBar ganha exp
                    jProgressBarLevel.setValue(ficha.getExp());
                }
            }
            
            // incrementando exp em exp nen
            CalculadoraTrainer.putExpLvlNen(AlgoritmoPrincipalTrainer.getEXP_NEN(lvlExp.getLvl()), ficha);
            jLabelNen.setText(String.valueOf(ficha.getLvlNen()));
            jProgressBarNen.setValue(ficha.getExpNen());
        }
        
        // setando valores na tabela
        // declarando variaveis
        DefaultTableModel dtm = (DefaultTableModel) jTable.getModel();
        int i = Integer.parseInt(jLabelDadosJogados.getText());
        Object[] vetor = {i, dado, lvlExp.getExp()};
        // removendo e inserindo valores na linha indicada pela label dadosJogados
        if (i <= 90) {
            dtm.removeRow(i - 1);
        }
        dtm.insertRow(i - 1, vetor);
        
        // limpando jTextField
        jTextFieldDado.selectAll();
        
        // avisando o usuario caso os dias de treino tiverem acabado
        if (Integer.parseInt(jLabelDadosRestantes.getText()) == 0) {
            JOptionPane.showMessageDialog(null, "Acabaram os dias de treino!",
                    "End Train!", JOptionPane.INFORMATION_MESSAGE);
            
            // se os dados de treino tiverem acabado, os campos são desativados
            desabilitandoCampos();
        }
    }
    
    private void jTextFieldQtdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQtdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            setQtdTreinos();
        }
    }//GEN-LAST:event_jTextFieldQtdKeyPressed

    private void jButtonQtdOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQtdOkActionPerformed
        setQtdTreinos();
    }//GEN-LAST:event_jButtonQtdOkActionPerformed

    private void jTextFieldDadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDadoFocusGained
        jTextFieldDado.selectAll();
    }//GEN-LAST:event_jTextFieldDadoFocusGained

    private void jTextFieldDadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDadoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            calculaExp();
        }
    }//GEN-LAST:event_jTextFieldDadoKeyPressed

    private void jButtonDadoOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDadoOkActionPerformed
        calculaExp();
    }//GEN-LAST:event_jButtonDadoOkActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        Treino treino = new Treino();
        double dias = Double.parseDouble(jLabelDadosJogados.getText()) / 2.0;
        String nome = jLabelNome.getText();

        treino.setNome(nome);
        treino.setDias(dias);

        AlgoritmoPrincipalTrainer.putTreino(Treino.getI(), treino);

        this.dispose();

    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jProgressBarLvlAtualMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProgressBarLvlAtualMouseEntered
        jProgressBarLvlAtual.setToolTipText(jProgressBarLvlAtual.getValue()+"/"+jProgressBarLvlAtual.getMaximum());
    }//GEN-LAST:event_jProgressBarLvlAtualMouseEntered

    private void jProgressBarLevelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProgressBarLevelMouseEntered
        jProgressBarLevel.setToolTipText(jProgressBarLevel.getValue()+"/"+jProgressBarLevel.getMaximum());
    }//GEN-LAST:event_jProgressBarLevelMouseEntered

    private void jProgressBarNenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProgressBarNenMouseEntered
        jProgressBarNen.setToolTipText(jProgressBarNen.getValue()+"/"+jProgressBarNen.getMaximum());
    }//GEN-LAST:event_jProgressBarNenMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_treinoNen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            View_treinoNen dialog = new View_treinoNen(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDadoOk;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonQtdOk;
    private javax.swing.JCheckBox jCheckBoxAteUpar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemOcultMessages;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDado;
    private javax.swing.JLabel jLabelDadosJogados;
    private javax.swing.JLabel jLabelDadosRestantes;
    private javax.swing.JLabel jLabelExpInicial;
    private javax.swing.JLabel jLabelLevel;
    private javax.swing.JLabel jLabelLvlAtual;
    private javax.swing.JLabel jLabelLvlInicial;
    private javax.swing.JLabel jLabelNen;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPer;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBarLevel;
    private javax.swing.JProgressBar jProgressBarLvlAtual;
    private javax.swing.JProgressBar jProgressBarNen;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTextFieldDado;
    private javax.swing.JTextField jTextFieldQtd;
    // End of variables declaration//GEN-END:variables

}
